# Generated by Django 2.2.2 on 2020-09-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentator',
            new_name='comment_by',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
