# Generated by Django 2.2.2 on 2020-09-09 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('highlight', models.CharField(max_length=300)),
                ('article', models.TextField()),
                ('slug', models.SlugField(max_length=270)),
                ('count', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('0', 'Lifestyle'), ('1', 'Fashion'), ('2', 'Travel'), ('3', 'Fitness'), ('4', 'Sports')], max_length=2)),
                ('image', models.ImageField(upload_to='uploads')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
